lib/intercom_stats_web/router.ex
defmodule IntercomStatsWeb.Router do
  use IntercomStatsWeb, :router
  use Coherence.Router
  use Plug.ErrorHandler
  use Sentry.Plug

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(Coherence.Authentication.Session)
  end

  pipeline :protected do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(Coherence.Authentication.Session, protected: true)
  end

  pipeline :graphql do
    plug(Plug.Parsers,
      parsers: [:urlencoded, :multipart, :json],
      pass: ["*/*"],
      json_decoder: Jason
    )

    plug(:fetch_session)
    plug(Coherence.Authentication.Session)
    plug(IntercomStatsWeb.Context)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/" do
    pipe_through(:browser)
    coherence_routes()
  end

  scope "/" do
    pipe_through(:protected)
    coherence_routes(:protected)
  end

  scope "/", IntercomStatsWeb do
    pipe_through(:browser)
  end

  scope "/", IntercomStatsWeb do
    pipe_through(:protected)

    get("/", PageController, :index)
    get("/get_from_api", PageController, :get_from_api)

    post("/", PageController, :search)

    get "/company/:name", CompanyController, :show
  end

  scope "/" do
    pipe_through(:graphql)

    forward("/graphiql", Absinthe.Plug.GraphiQL,
      schema: IntercomStatsWeb.Schema,
      interface: :simple,
      socket: IntercomStatsWeb.UserSocket
    )

    forward("/", Absinthe.Plug, schema: IntercomStatsWeb.Schema)
  end
end

lib/intercom_stats_web/templates/page/index.html.eex
  <div class="w-100 d-flex">
    <%= form_for @conn, page_path(@conn, :search), [as: :search, class: "d-flex align-items-md-center"], fn f -> %>
      <label class="align-self-end mr-2">
        <div><%= gettext("Van") %></div>
        <%= text_input f,
          :from_date,
          type: :date,
          min: "2017-07-01",
          value: @model.search.from_date,
          class: "form-control" %>
      </label>
      <label class="align-self-end mr-2">
        <div><%= gettext("tot") %></div>
        <%= text_input f,
          :to_date,
          type: :date,
          value: @model.search.to_date,
          class: "form-control" %>
      </label>
      <div class="d-flex align-self-end mb-2">
        <%= submit gettext("Search"), class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>

  <div class="content mt-3 mb-3">
    <div class="card">
      <div class="card-header"><%= gettext("Gemiddelde eerste reactietijd") %></div>
      <div class="card-body">
        <h5 class="card-title"><%= @model.average_response_time %></h5>
      </div>
    </div>

    <div class="card">
      <div class="card-header"><%= gettext("Gemiddelde sluittijd") %></div>
      <div class="card-body">
        <h5 class="card-title"><%= @model.average_closing_time %></h5>
      </div>
    </div>

    <div class="card">
      <div class="card-header"><%= gettext("Aantal Meldingen") %></div>
      <div class="card-body">
        <h5 class="card-title"><%= @model.number_of_messages %></h5>
      </div>
    </div>
  </div>

  <table class="table">
    <thead class="thead-light">
      <tr>
        <th scope="col"><%= gettext("Klant") %></th>
        <th scope="col"><%= gettext("Gemiddelde eerste reactietijd") %></th>
        <th scope="col"><%= gettext("Gemiddelde sluittijd") %></th>
      </tr>
    </thead>
    <tbody>
      <%= for group <- @model.averages_per_company do %>
        <tr>
          <th scope="row">
            <%= link(group.company_name, to: company_path(@conn,
                                                          :show,
                                                          group.company_name,
                                                          from_date: @model.search.from_date,
                                                          to_date: @model.search.to_date)) %></th>
          <td><%= group.average_first_response %></td>
          <td><%= group.average_closing_time %></td>
        </tr>
      <% end %>
    </tbody>
  </table>